### ISSUE TITLE
Unofficial适配。

### ISSUE THREAD

**Issue by h0we** [okcar-os/android#1]
Unofficial是否有开发者讨论群。

**Comment by leohuangyi** [comment]
节后会进行相关开发群、WiKi文档之类的工作，之前赶系统大家加班太多先休息下

**Comment by h0we** [comment]
> 节后会进行相关开发群、WiKi文档之类的工作，之前赶系统大家加班太多先休息下

我适配了一些机器，当前遇到的问题是 去连接车机的时候，默认是走的USB调试 点击OKCAR后消失 ，因条件限制 无法获取log 建议开放群。且核心组件是否有开源的计划？

**Comment by leohuangyi** [comment]
这说明 USB config prop 设置之后没有切换成功，https://github.com/okcar-os/android_device_xiaomi_sm8350-common/commit/2187a99055c9022bb8f147608b22e6b5d7b827ae
类似这一步修改做了么，找到对应机器的 device common project 把 usb prop 监听的.rc 文件载入

把 usb config 切换成 okcar 目的是让设备的 usb 描述符和 iPhone 一致 这里还用不到连接日志.设置成功的标致是电脑主机使用 lsusb 看到 手机 USB 描述符和 iPhone 一致说明设置成功了.只有这样车机那边才会开始 CarPlay 会话

日志部分后续文档会整理好

**Comment by leohuangyi** [comment]
> Unofficial是否有开发者讨论群。

QQ 群： 450574045

**Comment by 0312birdzhang** [comment]
> 这说明 USB config prop 设置之后没有切换成功，[okcar-os/android_device_xiaomi_sm8350-common@2187a99](https://github.com/okcar-os/android_device_xiaomi_sm8350-common/commit/2187a99055c9022bb8f147608b22e6b5d7b827ae) 类似这一步修改做了么，找到对应机器的 device common project 把 usb prop 监听的.rc 文件载入
> 
> 把 usb config 切换成 okcar 目的是让设备的 usb 描述符和 iPhone 一致 这里还用不到连接日志.设置成功的标致是电脑主机使用 lsusb 看到 手机 USB 描述符和 iPhone 一致说明设置成功了.只有这样车机那边才会开始 CarPlay 会话
> 
> 日志部分后续文档会整理好

这个问题是原因是 https://github.com/okcar-os/okcar 项目没有正常编译，在out/target/product/$DEVICE/vendor/etc/hw 下面没有okcar的俩init文件

**Comment by leohuangyi** [comment]
> > 这说明 USB config prop 设置之后没有切换成功，[okcar-os/android_device_xiaomi_sm8350-common@2187a99](https://github.com/okcar-os/android_device_xiaomi_sm8350-common/commit/2187a99055c9022bb8f147608b22e6b5d7b827ae) 类似这一步修改做了么，找到对应机器的 device common project 把 usb prop 监听的.rc 文件载入
> > 把 usb config 切换成 okcar 目的是让设备的 usb 描述符和 iPhone 一致 这里还用不到连接日志.设置成功的标致是电脑主机使用 lsusb 看到 手机 USB 描述符和 iPhone 一致说明设置成功了.只有这样车机那边才会开始 CarPlay 会话
> > 日志部分后续文档会整理好
> 
> 这个问题是原因是 https://github.com/okcar-os/okcar 项目没有正常编译，在out/target/product/$DEVICE/vendor/etc/hw 下面没有okcar的俩init文件

[okcar](https://github.com/okcar-os/okcar)项目没有正常编译的话，ROM中是没有OKCAR互联、OKCAR市场、OK桌面这几个应用的，如果有这几个应用说明是编译成功的。
目前我本地编译来看是正常的，节后我再重新拉取repo sync一次看看是否正常

**Comment by 0312birdzhang** [comment]
是的，没有那几个包安装，不过我是移植的别的机型，而且开源的设备device代码也是commom，不确定少了什么模块。

目前开机进不去桌面，显示“正在进入Android”系统，感觉就是少了okcar那部分，其他的都正常。

**Comment by leohuangyi** [comment]
> 是的，没有那几个包安装，不过我是移植的别的机型，而且开源的设备device代码也是commom，不确定少了什么模块。
> 
> 目前开机进不去桌面，显示“正在进入Android”系统，感觉就是少了okcar那部分，其他的都正常。

下午重新拉取并编译了，可以确定已有机型新拉取、编译、链接车机是没有问题。

编译完成后检查out/target/product/XX/vendor/etc/init/hw/init.qcom.okcar.rc是否存在，若不存可能是项目没有完全同步完成或者还在别的分支，[okcar项目](https://github.com/okcar-os/okcar)的资源引入是通过https://github.com/okcar-os/android_vendor_lineage/commit/d13df1792745816c3b018584de31baf1c5861f2a  引入的

**Comment by 0312birdzhang** [comment]
好的，很关键的信息，节后回家再试试，谢谢
