### ISSUE TITLE
蓝牙接收器

### ISSUE THREAD

**Issue by hjchjchjc4352** [okcar-os/android#10]
Android13能否开启a2dp sink功能作为蓝牙接收器，这样可以接受其他设备蓝牙音频，不然carplay占用蓝牙通道，主力机无法蓝牙通话

**Comment by leohuangyi** [comment]
a2dp sink、hfp协议都可以开启，但是支持并不完整，尤其是hfp音频路由那块，完全是不通的，适配是一块很大的工作量，需要精通蓝牙协议、Android音频路由，暂无法实现
