### ISSUE TITLE
不兼容瑞虎5x 2020时尚  车机carplay

### ISSUE THREAD

**Issue by cdbvv** [okcar-os/android#11]
瑞虎5x 2020 自动挡时尚 ，手机是红米note8 okcar版本：okcar_os-TQ3A.231109.005-ginkgo-stable-11_10-rom.zip
连接上车机后手机有连接提示，一会就消失了。车机完全没有反应，不显示有usb设备连接。试了很多次都没有反应

**Comment by leohuangyi** [comment]
月底会更新一个新版本，请更新后再试试，如果还是不行请加Q 1677984685，技术远程调试适配。
