### ISSUE TITLE
能不能支持carlife或者易连

### ISSUE THREAD

**Issue by leon-790** [okcar-os/android#12]
能不能支持carlife或者易连。carplay好歹有苹果手机支持，carlife才是最惨的，目前也就ov支持的比较好。你们如果能支持carlife，那可用性就高很多了。

**Comment by leohuangyi** [comment]
协议适配有很大的工作量，CarPlay协议这块我们搞了2年多才稳定，不同的车型有不同的情况，光车机就买了10几套，期间还不断和不同车型的车友远程联调。目前我们的重心是把CarPlay车型适配做好，系统做好，有一定用户量了能维持团队的运作了才有时间和成本去研发别的通道。
