### ISSUE TITLE
希望能够增加Androidauto通道支持

### ISSUE THREAD

**Issue by hjchjchjc4352** [okcar-os/android#13]
类似此类盒子，感觉技术上可以实现
https://www.bilibili.com/video/av448943178?p=1&unique_k=114514
原因有以下
1.走aa流畅度不逊于carplay，支持多点
2.蓝牙可以曲线救国车载通话，音频的很多问题都能迎刃而解
3.兼容性稳定性可能会好一些，毕竟安卓机子都可以连接
虽然carplay用户较多，但支持aa的车子其实也不在少数，只是大家都不用显得没人知道，可能aa维护的工作量会比carplay要小一些

**Comment by leohuangyi** [comment]
协议适配有很大的工作量，CarPlay协议这块我们搞了2年多才稳定，不同的车型有不同的情况，光车机就买了10几套，期间还不断和不同车型的车友远程联调，没有开放的资料做协议逆向很苦B，CarPlay没有，Android Auto也没有。目前我们的重心是把CarPlay车型适配做好，系统做好，有一定用户量了能维持团队的运作了才有时间和成本去研发别的通道。
