### ISSUE TITLE
连接方式

### ISSUE THREAD

**Issue by Flat-Chen** [okcar-os/android#15]
大佬大佬，目前是只支持有线carplay连接方式吗
蓝牙+wifi的无线carplay连接方式能支持吗

**Comment by leohuangyi** [comment]
部分车型比如宝马只支持无线CarPlay，无线CarPlay年后我们会开始支持，需要一定的研发周期

**Comment by Flat-Chen** [comment]
> 部分好像宝马只支持无线CarPlay，无线CarPlay以后我们会开始支持，需要一定的研发周期

万分感谢
