### ISSUE TITLE
repo sync stuck and eventually failed

### ISSUE THREAD

**Issue by Praween** [okcar-os/android#16]
Repo sync stuck at (1240/1244)  9:20:45 | 1 job  8:25:36  okcar-os/android_bootable_recovery @ bootable/recovery 

error: Cannot fetch okcar-os/android_bootable_recovery from https://github.com/okcar-os/android_bootable_recovery

for 8+ hours and eventually failed.

**Comment by Praween** [comment]
<project path="bootable/recovery" name="okcar-os/android_bootable_recovery" groups="pdk" remote="okcar-os" />

**Comment by Praween** [comment]
Hi,

Can someone please respond to this email?

**Comment by leohuangyi** [comment]
> Repo sync stuck at (1240/1244) 9:20:45 | 1 job 8:25:36 okcar-os/android_bootable_recovery @ bootable/recovery
> 
> error: Cannot fetch okcar-os/android_bootable_recovery from https://github.com/okcar-os/android_bootable_recovery
> 
> for 8+ hours and eventually failed.

Forgot to make it public, now it has been made public.

**Comment by Liliniser** [comment]
I guess android_tools_extract-utils also needs to be public

**Comment by leohuangyi** [comment]
> I guess android_tools_extract-utils also needs to be public

you are right. it public now.
