### ISSUE TITLE
Source code sync is failing!!!

### ISSUE THREAD

**Issue by Praween** [okcar-os/android#7]
Hi,
Getting these issue,

1. Syntax is wrong :  --git-lfs
2. Syntax Error : Invalid syntax

```
core@test:~/CarplayOK$ repo init -u https://github.com/okcar-os/android.git -b okcar-1.0 --git-lfs
Usage: repo init -u url [options]

repo: error: no such option: --git-lfs
core@test:~/CarplayOK$ repo init -u https://github.com/okcar-os/android.git -b okcar-1.0 -git-lfs
warning: gpg (GnuPG) is not available.
warning: Installing it is strongly encouraged.

warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
  File "/home/core/CarplayOK/.repo/repo/main.py", line 94
    )
    ^
SyntaxError: invalid syntax
```
Please help to unblock the code sync.

**Comment by emvia** [comment]
try to install repo manualy

> export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
gpg --recv-keys 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO} && install -m 755 ${REPO} ~/bin/repo

see google repo readme https://source.android.com/setup/develop#installing-repo

**Comment by leohuangyi** [comment]
> try to install repo manualy
> 
> > export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
> > curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
> > gpg --recv-keys 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
> > curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO} && install -m 755 ${REPO} ~/bin/repo
> 
> see google repo readme https://source.android.com/setup/develop#installing-repo

Yes，you need update latest repo cmd.
